name: Ejecutar Checkeo de Empleados
on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Llamada de checkeo de expiracion de empleado
        run: |
          # El token se concatena de forma segura en la URL
          curl -X GET "http://legalauditex.ar/cron/check-expired-employees?token=${{ secrets.DEPLOY_TOKEN }}"