name: Ejecutar Tareas Laravel
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar Endpoint Protegido
        run: |
          # El token se concatena de forma segura en la URL
          curl -X GET "http://legalauditex.ar/cron/check-expired-employees?token=${{ secrets.CRON_TOKEN }}"